#!/bin/bash

cd $(dirname $0)

for DIR in test/source/* ; do
for FILE in $DIR/impl/*.pas ; do
	DIRNAME=$(basename $DIR)
	FILENAME=$(basename $FILE .pas)
	echo -e "\n# $DIRNAME/$FILENAME"

	TMPDIR=$(mktemp -d)

	mkdir $TMPDIR/fpc_obj
	mkdir $TMPDIR/ghc_obj
	mkdir $TMPDIR/fpc_bin
	mkdir $TMPDIR/ghc_bin
	DIR_DEST=test/dest/$DIRNAME
	mkdir -p $DIR_DEST
	FILE_DEST=$DIR_DEST/$FILENAME.hs
	cabal run $FILE $FILE_DEST &> $TMPDIR/compile_out &&
	fpc -FE$TMPDIR/fpc_bin -FU$TMPDIR/fpc_obj $FILE &> $TMPDIR/compile_out &&
	ghc $FILE_DEST -outputdir $TMPDIR/ghc_obj -o $TMPDIR/ghc_bin/$FILENAME &> $TMPDIR/compile_out
	if [ $? != 0 ] ; then
		echo -e "\t!! error in $FILENAME"
		cat $TMPDIR/compile_out
	else
		FILES_IN=$DIR/test_in
		if [ -d "$FILES_IN" ] ; then
			FILES_IN=$FILES_IN/*
		else
			FILES_IN=/dev/null
		fi

		for FILEIN in $FILES_IN ; do
			FILEINNAME=$(basename $FILEIN)
			SOURCE_OUT=$TMPDIR/source_out
			echo -e "\t!! test " $FILEINNAME &&
			$TMPDIR/fpc_bin/$FILENAME < $FILEIN > $TMPDIR/source_out &&
			$TMPDIR/ghc_bin/$FILENAME < $FILEIN > $TMPDIR/dest_out &&
			diff -y --suppress-common-lines $TMPDIR/source_out $TMPDIR/dest_out
		done
	fi
	rm -r $TMPDIR
done
done
