#!/bin/bash

ghc source/Main.hs -O2 -threaded -with-rtsopts="-N" -outputdir build -isource -o exe &&
for FILE in ./test/source/*.pas
do
	FILENAME=$(basename $FILE .pas)
	echo -e '\n'
	echo '-----------------' $FILENAME '-----------------'
	./exe $FILE ./test/dest/$FILENAME.hs &&
	echo "-----------------FPC-----------------" &&
	fpc -FE./test/source/bin -FU./test/source/obj $FILE &&
	echo "-----------------GHC-----------------" &&
	ghc ./test/dest/$FILENAME.hs -outputdir ./test/dest/obj/ -o ./test/dest/bin/$FILENAME &&
	./test/source/bin/$FILENAME < ./test/input/$FILENAME.in > ./test/source/$FILENAME.out &&
	./test/dest/bin/$FILENAME < ./test/input/$FILENAME.in > ./test/dest/$FILENAME.out &&
	echo "-----------------diff " $FILENAME "-----------------" &&
	diff -y ./test/source/$FILENAME.out ./test/dest/$FILENAME.out
done
exit $?
